services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - nginx-network

  app:
    build: .
    container_name: app
    environment:
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      SUPER_ADMIN_USER: ${SUPER_ADMIN_USER}
      SUPER_ADMIN_EMAIL: ${SUPER_ADMIN_EMAIL}
      SUPER_ADMIN_PASS: ${SUPER_ADMIN_PASS}
    volumes:
      - ./app:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nginx-network
      - db-network

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 3s
      timeout: 2s
    networks:
      - s3-network
      - db-network

  s3master:
    image: chrislusf/seaweedfs
    container_name: seaweedfs_master
    command: master
    networks:
      - s3-network

  s3volume:
    image: chrislusf/seaweedfs
    container_name: seaweedfs_volume
    command: volume -mserver="s3master:9333" -port=8080
    volumes:
      - ./s3:/data
    networks:
      - s3-network

  s3filer:
    image: chrislusf/seaweedfs
    container_name: seaweedfs_filer
    command: filer -master="s3master:9333"
    depends_on:
      - s3master
      - s3volume
    networks:
      - s3-network
      - nginx-network

networks:
  nginx-network:
    driver: bridge
  db-network:
    driver: bridge
  s3-network:
    driver: bridge