server {
    listen 80;
    server_name localhost;

    client_max_body_size 20M;

    resolver 127.0.0.11 valid=30s;

    location /data/ {
        limit_except GET {
            deny all;
        }

        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass_request_headers on;

        proxy_pass http://s3filer:8888/;

        proxy_intercept_errors on;

        proxy_cache_valid 200 302 24h;
        expires 24h;
    }

    location / {
        proxy_pass http://app:80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}